services:

  # ---------------------------------------------------------------
  # BACKEND SERVICES
  # ---------------------------------------------------------------

  postgres:
    image: "postgres:16-alpine"
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
